development: &development
    access_key_id:       "abc"
    secret_access_key:   "abc"
    s3_endpoint:         "localhost"
    s3_port:             10001
    s3_force_path_style: true
    use_ssl:             false

test: *development


production: &production
    access_key_id:     <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

staging: *production