development: &development
    storage:       :s3
    bucket:        "development"
    s3_host_name:  "localhost"
    url:           ":s3_alias_url"
    path:          ":class/:attachment/:id_partition/:style/:filename.:extension"
    s3_host_alias: "localhost:10001/development"

test: *development

production: &production
    storage: :s3
    bucket:  <%= ENV["S3_BUCKET_NAME"] %>
    url:     ":afrikart.s3-eu-west-1.amazonaws.com"
    path:    ":class/:attachment/:id_partition/:style/:filename.:extension"

staging: *production